@startuml

title __QLOG's Class Diagram__\n

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.ConnectionQLog {
          - cid : byte[]
          - closed : boolean
          - jsonGenerator : JsonGenerator
          - startTime : Instant
          + ConnectionQLog()
          + close()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          - emitConnectionClosedEvent()
          - emitMetrics()
          - format()
          - formatPacketType()
          - writeFooter()
          - writeHeader()
          - writePacketEvent()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.FrameFormatter {
          - jsonGenerator : JsonGenerator
          + FrameFormatter()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          + process()
          - format()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.NullQLog {
          + emitCongestionControlMetrics()
          + emitConnectionClosedEvent()
          + emitConnectionClosedEvent()
          + emitConnectionCreatedEvent()
          + emitConnectionTerminatedEvent()
          + emitPacketReceivedEvent()
          + emitPacketSentEvent()
          + emitPacketSentEvent()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      interface net.luminis.quic.qlog.QLog {
          {abstract} + emitCongestionControlMetrics()
          {abstract} + emitConnectionClosedEvent()
          {abstract} + emitConnectionClosedEvent()
          {abstract} + emitConnectionCreatedEvent()
          {abstract} + emitConnectionTerminatedEvent()
          {abstract} + emitPacketReceivedEvent()
          {abstract} + emitPacketSentEvent()
          {abstract} + emitPacketSentEvent()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.QLogBackEnd {
          - connections : Map<byte[], ConnectionQLog>
          - queue : BlockingQueue<QLogEvent>
          + QLogBackEnd()
          + getQueue()
          - generateConnectionLog()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      abstract class net.luminis.quic.qlog.QLogEvent {
          - cid : byte[]
          - time : Instant
          + QLogEvent()
          {abstract} + accept()
          + getCid()
          + getTime()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.QLogFrontEnd {
          - eventQueue : Queue<QLogEvent>
          - originalDcid : byte[]
          + QLogFrontEnd()
          + emitCongestionControlMetrics()
          + emitConnectionClosedEvent()
          + emitConnectionClosedEvent()
          + emitConnectionCreatedEvent()
          + emitConnectionTerminatedEvent()
          + emitPacketReceivedEvent()
          + emitPacketSentEvent()
          + emitPacketSentEvent()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      class net.luminis.quic.qlog.QLogFrontEnd.NullQueue {
          + add()
          + addAll()
          + clear()
          + contains()
          + containsAll()
          + element()
          + isEmpty()
          + iterator()
          + offer()
          + peek()
          + poll()
          + remove()
          + remove()
          + removeAll()
          + retainAll()
          + size()
          + toArray()
          + toArray()
      }
    }
  }
  

  net.luminis.quic.qlog.ConnectionQLog .up.|> net.luminis.quic.qlog.event.QLogEventProcessor
  net.luminis.quic.qlog.ConnectionQLog o-- net.luminis.quic.qlog.FrameFormatter : frameFormatter
  net.luminis.quic.qlog.FrameFormatter .up.|> net.luminis.quic.frame.FrameProcessor3
  net.luminis.quic.qlog.NullQLog .up.|> net.luminis.quic.qlog.QLog
  net.luminis.quic.qlog.QLogFrontEnd .up.|> net.luminis.quic.qlog.QLog
  net.luminis.quic.qlog.QLogFrontEnd +-down- net.luminis.quic.qlog.QLogFrontEnd.NullQueue
  net.luminis.quic.qlog.QLogFrontEnd.NullQueue .up.|> java.util.Queue


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
