@startuml

title __H09's Class Diagram__\n

  namespace net.luminis.quic {
    namespace client.h09 {
      class net.luminis.quic.client.h09.Http09Client {
          - connectionTimeout : int
          - executorService : ExecutorService
          - with0RTT : boolean
          + Http09Client()
          + authenticator()
          + connectTimeout()
          + cookieHandler()
          + executor()
          + followRedirects()
          + proxy()
          + send()
          + sendAsync()
          + sendAsync()
          + sslContext()
          + sslParameters()
          + version()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace client.h09 {
      class net.luminis.quic.client.h09.Http09Client.AsyncHttpRequest {
          - request : HttpRequest
          - responseBodyHandler : BodyHandler<T>
          + AsyncHttpRequest()
          + cancel()
          + run()
          + start()
          - send()
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace client.h09 {
      class net.luminis.quic.client.h09.HttpResponseImpl {
          - request : HttpRequest
          + HttpResponseImpl()
          + body()
          + headers()
          + previousResponse()
          + request()
          + sslSession()
          + statusCode()
          + uri()
          + version()
      }
    }
  }
  

  net.luminis.quic.client.h09.Http09Client -up-|> java.net.http.HttpClient
  net.luminis.quic.client.h09.Http09Client o-- net.luminis.quic.QuicClientConnection : quicConnection
  net.luminis.quic.client.h09.Http09Client +-down- net.luminis.quic.client.h09.Http09Client.AsyncHttpRequest
  net.luminis.quic.client.h09.Http09Client.AsyncHttpRequest -up-|> java.util.concurrent.CompletableFuture
  net.luminis.quic.client.h09.Http09Client.AsyncHttpRequest o-- net.luminis.quic.QuicStream : httpStream
  net.luminis.quic.client.h09.HttpResponseImpl .up.|> java.net.http.HttpResponse
  net.luminis.quic.client.h09.HttpResponseImpl o-- T : body


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
