@startuml

title __EVENT's Class Diagram__\n

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.CongestionControlMetricsEvent {
            - bytesInFlight : long
            - congestionWindow : long
            + CongestionControlMetricsEvent()
            + accept()
            + getBytesInFlight()
            + getCongestionWindow()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.ConnectionClosedEvent {
            - errorReason : String
            - transportErrorCode : Integer
            + ConnectionClosedEvent()
            + ConnectionClosedEvent()
            + accept()
            + getErrorReason()
            + getTransportErrorCode()
            + getTrigger()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        enum Trigger {
          idleTimeout
          immediateClose
          qlogFormat
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.ConnectionCreatedEvent {
            + ConnectionCreatedEvent()
            + accept()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.ConnectionTerminatedEvent {
            + ConnectionTerminatedEvent()
            + accept()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        abstract class net.luminis.quic.qlog.event.PacketEvent {
            + PacketEvent()
            + getPacket()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.PacketReceivedEvent {
            + PacketReceivedEvent()
            + accept()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        class net.luminis.quic.qlog.event.PacketSentEvent {
            + PacketSentEvent()
            + accept()
        }
      }
    }
  }
  

  namespace net.luminis.quic {
    namespace qlog {
      namespace event {
        interface net.luminis.quic.qlog.event.QLogEventProcessor {
            {abstract} + process()
            {abstract} + process()
            {abstract} + process()
            {abstract} + process()
            {abstract} + process()
            {abstract} + process()
        }
      }
    }
  }
  

  net.luminis.quic.qlog.event.CongestionControlMetricsEvent -up-|> net.luminis.quic.qlog.QLogEvent
  net.luminis.quic.qlog.event.ConnectionClosedEvent -up-|> net.luminis.quic.qlog.QLogEvent
  net.luminis.quic.qlog.event.ConnectionClosedEvent o-- net.luminis.quic.qlog.event.ConnectionClosedEvent.Trigger : trigger
  net.luminis.quic.qlog.event.ConnectionClosedEvent +-down- net.luminis.quic.qlog.event.ConnectionClosedEvent.Trigger
  net.luminis.quic.qlog.event.ConnectionCreatedEvent -up-|> net.luminis.quic.qlog.QLogEvent
  net.luminis.quic.qlog.event.ConnectionTerminatedEvent -up-|> net.luminis.quic.qlog.QLogEvent
  net.luminis.quic.qlog.event.PacketEvent -up-|> net.luminis.quic.qlog.QLogEvent
  net.luminis.quic.qlog.event.PacketEvent o-- net.luminis.quic.packet.QuicPacket : packet
  net.luminis.quic.qlog.event.PacketReceivedEvent -up-|> net.luminis.quic.qlog.event.PacketEvent
  net.luminis.quic.qlog.event.PacketSentEvent -up-|> net.luminis.quic.qlog.event.PacketEvent


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
